### ISSUE TITLE
Add types or interfaces describing REST API responses

### ISSUE THREAD

**Issue by Shelob9** [johnbillion/wp-types#9]
@johnbillion I wanted to continue this discussion: https://github.com/WP-API/node-wpapi/issues/149#issuecomment-629792627 I'm sorry for the delayed response. Life happened.

I found the types I had started: 

* https://github.com/Shelob9/wp-like-site/blob/master/packages/use-wordpress/src/types.ts
* https://github.com/Shelob9/wp-like-site/blob/master/packages/use-wordpress/src/wpTypes.ts

It's challenging, beacuse the WordPress REST API is so extensible. The node-wpapi generates dynamic schemas, per site, which is cool. I am not sure how to provide a "standard" defintion of something that can be different on any site.

**Comment by johnbillion** [comment]
Thanks Josh, that's a good start.

I changed this library a few days ago so its interfaces are all generated from [wp-json-schemas](https://www.npmjs.com/package/wp-json-schemas), so if the default schemas in an OPTIONS request to the REST API are correct (ie. with `additionalProperties` set to true) then we should be okay. Or we can tweak the TS interfaces accordingly so they fit the default schema for a vanilla site.

**Comment by johnbillion** [comment]
I've added definitions for posts and users in b958d04. Like the rest of this library, these are generated from [wp-json-schemas](https://www.npmjs.com/package/wp-json-schemas) and are based only on the default endpoints on a vanilla site.

For now, most property definitions are part of the main `User` or `Post` object, but I think splitting them out like you did in your definitions has value.
